# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3573cf57ea9cd0c15e3438c6ca9c90e58eaf2f9cf0b5f944a65f9e40ce62e3888ebcde4c569e3e2493dcc16dfcb24c68dce616b46f3fee1c29608cd455353163

test:
  secret_key_base: 61900295eecbd3f8564272d4f852a337b26cf8cefb3aa94bc541e902f38df1a7485d1fa74b46c08efe3c93b66c022bf86f8c97848730cfe8b6af408b1e86415b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
